#TargetName:Dependencies
#<TAB>commands

Build:snake_and_ladder.c
	gcc snake_and_ladder.c -o snake_and_ladder.out

Run:snake_and_ladder.out
	./snake_and_ladder.out

Clean:
	rm -rf  *.o *.out *.i *.s
	